"""create initial schema

Revision ID: 001
Revises: 
Create Date: 2025-09-01 15:59:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_cycles_label'), 'billing_cycles', ['label'], unique=True)
    op.create_index(op.f('ix_billing_cycles_status'), 'billing_cycles', ['status'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('CONSUMER', 'PROSUMER', 'OPERATOR', name='role'), nullable=False),
    sa.Column('iban', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_api_key'), 'participants', ['api_key'], unique=False)
    op.create_index(op.f('ix_participants_created_at'), 'participants', ['created_at'], unique=False)
    op.create_index(op.f('ix_participants_external_id'), 'participants', ['external_id'], unique=True)
    op.create_index(op.f('ix_participants_role'), 'participants', ['role'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('hash_hex', sa.String(length=128), nullable=False),
    sa.Column('signature', sa.String(length=512), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_hex')
    )
    op.create_index(op.f('ix_policies_version'), 'policies', ['version'], unique=True)
    op.create_table('settlement_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['billing_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_runs_cycle_id'), 'settlement_runs', ['cycle_id'], unique=False)
    op.create_table('trading_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('date_str', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['billing_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_days_cycle_id'), 'trading_days', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_trading_days_date_str'), 'trading_days', ['date_str'], unique=False)
    op.create_index(op.f('ix_trading_days_status'), 'trading_days', ['status'], unique=False)
    op.create_table('explain_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('trace_json', sa.Text(), nullable=False),
    sa.Column('trace_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['billing_cycles.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explain_traces_cycle_id'), 'explain_traces', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_explain_traces_participant_id'), 'explain_traces', ['participant_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('amount_eur', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['billing_cycles.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_created_at'), 'ledger_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_ledger_entries_cycle_id'), 'ledger_entries', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_event_ts'), 'ledger_entries', ['event_ts'], unique=False)
    op.create_index(op.f('ix_ledger_entries_participant_id'), 'ledger_entries', ['participant_id'], unique=False)
    op.create_index('ix_ledger_cycle_participant', 'ledger_entries', ['cycle_id', 'participant_id'], unique=False)
    op.create_table('payout_instructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('iban', sa.String(length=64), nullable=False),
    sa.Column('amount_eur', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('remittance_info', sa.String(length=140), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['settlement_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_instructions_participant_id'), 'payout_instructions', ['participant_id'], unique=False)
    op.create_index(op.f('ix_payout_instructions_run_id'), 'payout_instructions', ['run_id'], unique=False)
    op.create_table('day_nets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('net_eur', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['trading_days.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_nets_day_id'), 'day_nets', ['day_id'], unique=False)
    op.create_index(op.f('ix_day_nets_participant_id'), 'day_nets', ['participant_id'], unique=False)
    op.create_table('internal_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('from_participant_id', sa.Integer(), nullable=False),
    sa.Column('to_participant_id', sa.Integer(), nullable=False),
    sa.Column('amount_eur', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['trading_days.id'], ),
    sa.ForeignKeyConstraint(['from_participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['to_participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_transfers_day_id'), 'internal_transfers', ['day_id'], unique=False)
    op.create_index(op.f('ix_internal_transfers_from_participant_id'), 'internal_transfers', ['from_participant_id'], unique=False)
    op.create_index(op.f('ix_internal_transfers_to_participant_id'), 'internal_transfers', ['to_participant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internal_transfers_to_participant_id'), table_name='internal_transfers')
    op.drop_index(op.f('ix_internal_transfers_from_participant_id'), table_name='internal_transfers')
    op.drop_index(op.f('ix_internal_transfers_day_id'), table_name='internal_transfers')
    op.drop_table('internal_transfers')
    op.drop_index(op.f('ix_day_nets_participant_id'), table_name='day_nets')
    op.drop_index(op.f('ix_day_nets_day_id'), table_name='day_nets')
    op.drop_table('day_nets')
    op.drop_index(op.f('ix_payout_instructions_run_id'), table_name='payout_instructions')
    op.drop_index(op.f('ix_payout_instructions_participant_id'), table_name='payout_instructions')
    op.drop_table('payout_instructions')
    op.drop_index('ix_ledger_cycle_participant', table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_participant_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_event_ts'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_cycle_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_created_at'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_explain_traces_participant_id'), table_name='explain_traces')
    op.drop_index(op.f('ix_explain_traces_cycle_id'), table_name='explain_traces')
    op.drop_table('explain_traces')
    op.drop_index(op.f('ix_trading_days_status'), table_name='trading_days')
    op.drop_index(op.f('ix_trading_days_date_str'), table_name='trading_days')
    op.drop_index(op.f('ix_trading_days_cycle_id'), table_name='trading_days')
    op.drop_table('trading_days')
    op.drop_index(op.f('ix_settlement_runs_cycle_id'), table_name='settlement_runs')
    op.drop_table('settlement_runs')
    op.drop_index(op.f('ix_policies_version'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_participants_role'), table_name='participants')
    op.drop_index(op.f('ix_participants_external_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_created_at'), table_name='participants')
    op.drop_index(op.f('ix_participants_api_key'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_billing_cycles_status'), table_name='billing_cycles')
    op.drop_index(op.f('ix_billing_cycles_label'), table_name='billing_cycles')
    op.drop_table('billing_cycles')
    # ### end Alembic commands ###